# Generated by Django 6.0.6 on 2026-06-27 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('coords', models.TextField(help_text='Pares x,y separados por coma, del image map.')),
            ],
            options={
                'ordering': ['numero'],
            },
        ),
    ]
