# Generated by Django 6.0.6 on 2026-06-27 21:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('territorio', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_familia', models.CharField(max_length=20)),
                ('nombre_familia', models.CharField(max_length=120)),
                ('integrantes', models.PositiveIntegerField(default=1)),
                ('contacto_1', models.CharField(blank=True, max_length=60)),
                ('contacto_2', models.CharField(blank=True, max_length=60)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('consentimiento_informado', models.BooleanField(default=False)),
                ('cargada_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familias_cargadas', to=settings.AUTH_USER_MODEL)),
                ('parcela', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='familias', to='territorio.parcela')),
            ],
        ),
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intencion', models.CharField(choices=[('PJ', 'PJ'), ('UCR', 'UCR'), ('Otro', 'Otro'), ('Indeciso', 'Indeciso'), ('No contesta', 'No contesta')], max_length=20)),
                ('familia', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='voto', to='encuestas.familia')),
            ],
        ),
    ]
